# Generated by Django 6.0.6 on 2026-07-05 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gegenstandsexemplar',
            name='verfuegbarkeitsstatus',
            field=models.CharField(choices=[('verfuegbar', 'Verfügbar'), ('nicht_verfuegbar', 'Nicht verfügbar')], default='verfuegbar', max_length=20),
        ),
        migrations.AlterField(
            model_name='gegenstandsexemplar',
            name='zustand',
            field=models.CharField(choices=[('neu', 'Neu'), ('gut', 'Gut'), ('beschaedigt', 'Beschädigt'), ('defekt', 'Defekt'), ('verloren', 'Verloren')], default='gut', max_length=20),
        ),
    ]
