# Generated by Django 6.0.6 on 2026-07-05 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_gegenstandsexemplar_verfuegbarkeitsstatus_and_more'),
        ('lending', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservierung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdatum', models.DateField()),
                ('enddatum', models.DateField()),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('aktualisiert_am', models.DateTimeField(auto_now=True)),
                ('is_seed', models.BooleanField(default=False)),
                ('ausleihanfrage_id', models.ForeignKey(db_column='ausleihanfrage_id', on_delete=django.db.models.deletion.CASCADE, to='lending.ausleihanfrage')),
                ('gegenstandsexemplar_id', models.ForeignKey(db_column='gegenstandsexemplar_id', on_delete=django.db.models.deletion.CASCADE, to='inventory.gegenstandsexemplar')),
                ('nutzer_id', models.ForeignKey(db_column='nutzer_id', on_delete=django.db.models.deletion.CASCADE, to='users.nutzer')),
            ],
            options={
                'db_table': 'reservierung',
            },
        ),
    ]
