# Generated by Django 6.0.6 on 2026-07-05 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_gegenstandsexemplar_verfuegbarkeitsstatus_and_more'),
        ('lending', '0002_reservierung'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservierung',
            name='reservierungsstatus',
            field=models.CharField(choices=[('offen', 'Offen'), ('bestaetigt', 'Bestätigt'), ('storniert', 'Storniert'), ('abgelehnt', 'Abgelehnt'), ('abgeschlossen', 'Abgeschlossen')], default='offen', max_length=20),
        ),
        migrations.AlterField(
            model_name='reservierung',
            name='gegenstandsexemplar_id',
            field=models.ForeignKey(db_column='gegenstandsexemplar_id', on_delete=django.db.models.deletion.CASCADE, related_name='reservierungen', to='inventory.gegenstandsexemplar'),
        ),
    ]
